# Site settings
title: Nicklas Ridewing
header-img: img/home-bg.jpg
email: nicklas@ridewing.se
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://ridewing.se"
twitter_username: ridewing
github_username:  ridewing
facebook_username:  ridewing

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
